FROM python:3.7-buster

# create directory for the app user
# RUN mkdir -p /home/app/midata
RUN mkdir /code

# set work directory
WORKDIR /code

# prevent python interpreter from writing of .pyc files and buffering of stdout/err
# equivalent to: `python -B -u`
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# EXPOSE 8000

RUN apt-get update && \
    apt-get -y upgrade  # && \
#    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /code/
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . /code/
